require('plugins')
require('settings')
require('telescope-setup')
require('mappings')
require('treesitter-setup')
require('lsp-setup')
require('null-ls-setup')
require('cmp-setup')
require('work')
-- require('coc-setup')
