vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
require 'globals'
require 'plugins'
require 'settings'
require 'telescope-setup'
require 'mappings'
require 'treesitter-setup'
require 'null-ls-setup'
require 'cmp-setup'
require 'work'
require 'nvim-tree-setup'
require 'octo-setup'
require 'jira-setup'
require 'luasnip-setup'
