return {
  'mustache/vim-mustache-handlebars',
  'moll/vim-node',
  'docunext/closetag.vim',
  'windwp/nvim-autopairs',
  'tomtom/tcomment_vim',
  'tomtom/tlib_vim',
  'MarcWeber/vim-addon-mw-utils',
  'tpope/vim-eunuch',
  'tpope/vim-fugitive',
  'tpope/vim-rhubarb',
  'tpope/vim-markdown',
  'tpope/vim-repeat',
  'tpope/vim-surround',
  'tpope/vim-unimpaired',
  'ntpeters/vim-better-whitespace',
  'schickling/vim-bufonly',
  'sheerun/vim-polyglot',
  'metakirby5/codi.vim',
  'github/copilot.vim',
  {
    'jcdickinson/http.nvim',
    build = 'cargo build --workspace --release',
  },
}
